#! /bin/bash
if [ -z "$DOCKER_REPO" ]; then
    echo "Error: please set \$DOCKER_REPO to your local repository's store of amazoncorretto:21.0.5-alpine3.20 or omit to fetch via proxy"
    exit 1
fi

if [-z "HTTP_PROXY" ]; then
    echo "Error: please set \$HTTP_PROXY"
    exit 1
fi

if [-z "HTTPS_PROXY" ]; then
    echo "Error: please set $HTTPS_PROXY"
    exit 1
fi

docker buildx build . --build-arg BASE_IMAGE=$DOCKER_REPO/eclipse-temurin:21 --build-arg HTTP_PROXY=$HTTP_PROXY --build-arg HTTPS_PROXY=$HTTPS_PROXY -t ghidra-xrefs-tool
