#! /bin/bash

/bin/frigg -l /share/frigg/windefs/win32.defs --analysis-scope=all-functions --xrefs-outfile /control-flow-recovery/output.xrefs --coverage-outfile /control-flow-recovery/output.drcov -o /control-flow-recovery/$1.html /control-flow-recovery/$1
cat /control-flow-recovery/output.xrefs
#sed -nr 's/(IMAGE_BASE=.*)/\1/p' /control-flow-recovery/$1.xml
#head -n 600 /control-flow-recovery/$1.xml | tail -n 400
while IFS= read -r line; do
    if [[ "$line" =~ "IMAGE_BASE" ]]; then
	echo "$line"
    fi
done < "/control-flow-recovery/$1.xml"
